version: '3.8'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: max
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: Diego
      MYSQL_PASSWORD: DiegoContrasena
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: mydatabase
      DB_USER: user
      DB_PASSWORD: userpassword

volumes:
  mysql-data: